{{< include preamble.qmd >}}

# Purpose {#sec-purpose}

> "[T]he mathematician's main reason for existence is to solve problems [...] therefore, what mathematics _really_ consists of is problems and solutions." 
>
> [@Halmos:1980ps]

Throughout your mathematics and scientific journey, you have likely encountered a variety of quantiative problems. Usually, these problems folllow a specific topic, technique, or method introduced in class that are followed by a series of related exercises to reinforce a particular concept or approach. In these instances, you may have been provided essential context to guide you toward the "appropriate" solution method. While this structued learning can solidify your understanding of a particular concept or approach, it can also be somewhat disconnected from reality. In real-world challenges, problems frequently integrate multiple concepts that span various areas of mathematics and quantitative reasoning, requiring a more holistic application of your knowledge.

In this module, our goal is to cultivate skills that enable you to tackle problems in a broader context. This goal will be achieved through action: we will develop problem solving skills and learn how to _solve problems more generally_ by ... solving problems! We will engage with tasks for which the solution methods are not predetermined. To succeed with these open-ended challenges, you will reflect on your experiences and the frameworks and processes you utilize in problem-solving. This reflection is crucial because effective problem-solving involves not just your mathematical resources (i.e., _what you know_), but also your perception of that knowledge shaped by your _experiences_ [@Schoenfeld:1985ps].

Ultimately, this problem solving module aims to:

- Build your confidence in solving unseen problems,
- Offers prompts to support reflection and deepen your perception of mathematical concepts and their interconnections,
- Provide generic support for scaffolding problem solving (vs scaffolding the problem) to enhance your problem-solving skills. 

Together, these aims will lay a foundation for your development as a mathematician and physicist.


:::{.callout-note collapse="true"}
## TL;DR

A key aspect of this module will involve engaging in problem-solving tasks, both individually and collaboratively, and reflecting on these experiences to enhance your learning.
:::

